### ISSUE TITLE
Ten typ map<string, bool> wypadałoby jakoś nazwać

### ISSUE THREAD

**Issue by ziobron** [bogkra/KataArgs#4]
https://github.com/bogkra/KataArgs/blob/8d3500e4d147bd46692bf5c71149cc92cabcba1a/src/args.hpp#L15

Pasowałoby
```
using Args = map<string, bool>;
```
Ale klasa nazywa się Args. Może tak:
```
using Flags = map<string, bool>;
```

**Comment by bogkra** [comment]
wow, to using prawie jak Pascal ;) No staje się c++ coraz czytelniejsze... :D

**Comment by bogkra** [comment]
w persons chyba też zdefiniowałem taki typ (bo coś się powtarzało) i napisałeś do tego issue. Może dlatego, że było przez typedef? typedef shared_ptr<Person> pp;
hm, a może dlatego, że było PO definicji klasy...

**Comment by bogkra** [comment]
eeee, < Person > znika w powyższym tekście, ale heca

**Comment by bogkra** [comment]
a może to nie było issue
